/// Flutter icons IParkingIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IParkingIcons
///      fonts:
///       - asset: fonts/IParkingIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IParkingIcons {
  IParkingIcons._();

  static const _kFontFam = 'IParkingIcons';
  static const String? _kFontPkg = null;

  static const IconData directions_car = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ip_close = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ipark_info = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_nav = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
