# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

include: package:total_lints/app.yaml

formatter:
  page_width: 120

linter:
  rules:
    prefer_relative_imports: true
    avoid_relative_lib_imports: true
    prefer_single_quotes: false
    prefer_double_quotes: true # I hate single quotes
    use_setters_to_change_properties: false
    lines_longer_than_80_chars: false # we use 120 (at least for now)
    sort_pub_dependencies: false # Tomek has a custom order
    require_trailing_commas: false # clashes with the new formatter

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/*.gform.dart"
    - "**/*.tailor.dart"
    - "**/*.gen.dart"
    - "**/*.graphql.dart"
    - "**/*.icons.dart"
    - "**/firebase_options.dart"
    - "lib/l10n/app_localizations*.dart"
  plugins:
    - custom_lint

custom_lint:
  rules:
    - provider_dependencies: false # this works weirdly
