include: package:solvro_config/app.yaml

plugins:
  riverpod_lint:
    version: ^3.1.4-dev.3
    diagnostics:
      provider_dependencies: false # this works weirdly
  solvro_config:
    version: ^1.8.3-dev
    diagnostics:
      provider_dependencies: false # this works weirdly
    haptic_wrappers:
      - AppHaptics. # only custom wrapper allowed
    haptic_owning_widgets:
      - ArrowButton
      - BaseSmallTileCard
      - BigPreviewCard
      - BranchBaseDialog
      - DepartmentCard
      - DigitalGuideNavLink
      - FiltersButton
      - MyFilterChip
      - MySplashTile
      - MyTextButton
      - NavigationTile
      - OfflineMessage
      - ParkingWideTileCard
      - PhotoTrailingWideTileCard
      - RedDialog
      - ScienceClubCard
      - SearchBox
      - SearchBoxAppBar
      - SmallTileCard
      - SubsectionHeader
      - TechnicalMessage
      - TileSplash
      - WideTileCard
      - _NavActionButton
      - _SksButton

analyzer:
  errors:
    unsafe_variance: ignore
