# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

include: package:total_lints/app.yaml

linter:
  rules:
    prefer_relative_imports: true
    avoid_relative_lib_imports: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/*.gform.dart"
    - "**/*.tailor.dart"
    - "**/*.gen.dart"
    - "**/*.graphql.dart"
