targets:
  $default:
    builders:
      theme_tailor:
        options:
          themes: [baseTheme]
          theme_getter: on_build_context_props
          require_static_const: true
      envied_generator:envied:
        generate_for:
          include:
            - lib/api_base/env.dart
