targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      envied_generator:envied:
        generate_for:
          include:
            - lib/config/env.dart
