name: widgetbook_workspace
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  topwr:
    path: ../
  flutter:
    sdk: flutter
  widgetbook: ^3.22.0
  widgetbook_annotation: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  widgetbook_generator: ^3.22.0
  build_runner: ^2.13.0
  solvro_config: ^1.3.0

flutter:
  uses-material-design: true
