// Scaffold generated by home_widget. Adjust the widget for your needs.

import WidgetKit
import SwiftUI

@main
struct CountdownHomeWidgetBundle: WidgetBundle {
  var body: some Widget {
    CountdownHomeWidget()
  }
}
