/// Flutter icons StrategicClubBadges
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StrategicClubBadges
///      fonts:
///       - asset: fonts/StrategicClubBadges.ttf
///
///
///
library;
import "package:flutter/widgets.dart";

class StrategicClubBadges {
  StrategicClubBadges._();

  static const _kFontFam = "StrategicClubBadges";
  static const String? _kFontPkg = null;

  static const IconData polish_badge = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData english_badge = IconData(0xe801, fontFamily: _kFontFam);
}
