/// Flutter icons BottomNavBarIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomNavBarIcons
///      fonts:
///       - asset: fonts/BottomNavBarIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class BottomNavBarIcons {
  BottomNavBarIcons._();

  static const _kFontFam = 'BottomNavBarIcons';
  static const String? _kFontPkg = null;

  static const IconData departments_icon = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_icon = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_icon = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_icon = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sci_clubs_icon = IconData(0xeb63, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view_grid = IconData(0xeba8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
