/// Flutter icons BottomNavBarIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomNavBarIcon
///      fonts:
///       - asset: fonts/BottomNavBarIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BottomNavBarIcon {
  BottomNavBarIcon._();

  static const _kFontFam = 'BottomNavBarIcon';
  static const String? _kFontPkg = null;

  static const IconData home_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faculty_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sci_circle_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
