// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU1JCqYFVCp0KVVDjAcEOhqBLsHfE2WeM',
    appId: '1:399902347530:web:9c8d0eb4e22dbbb7db2af3',
    messagingSenderId: '399902347530',
    projectId: 'topwr-a2066',
    authDomain: 'topwr-a2066.firebaseapp.com',
    storageBucket: 'topwr-a2066.appspot.com',
    measurementId: 'G-0B5HMNSE0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR3ysGBw3Nz5L85-rfgSGH_4RWlEUHDPM',
    appId: '1:399902347530:android:54f57104b4011528db2af3',
    messagingSenderId: '399902347530',
    projectId: 'topwr-a2066',
    storageBucket: 'topwr-a2066.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaDwyDAki28oTuwVc4Vg9_ZYQClzChxWE',
    appId: '1:399902347530:ios:46a00f036bf46d80db2af3',
    messagingSenderId: '399902347530',
    projectId: 'topwr-a2066',
    storageBucket: 'topwr-a2066.appspot.com',
    iosClientId: '399902347530-1pdnhl4c0fmk62pulk4vomp5jbd0ovcj.apps.googleusercontent.com',
    iosBundleId: 'com.solvro.ToPwr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaDwyDAki28oTuwVc4Vg9_ZYQClzChxWE',
    appId: '1:399902347530:ios:3f66b1b8f9cc9742db2af3',
    messagingSenderId: '399902347530',
    projectId: 'topwr-a2066',
    storageBucket: 'topwr-a2066.appspot.com',
    iosBundleId: 'pl.edu.pwr.solvro.topwrMobile.RunnerTests',
  );
}
