# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new intenal build to TestFlight for internal testers"
  lane :internal do
    setup_ci if ENV["CI"]

    # Use App Store Connect API Key in CI
    api_key = nil
    if ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"] && ENV["APP_STORE_CONNECT_API_KEY_KEY_PATH"]
      api_key = app_store_connect_api_key(
        key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
        issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
        key_filepath: ENV["APP_STORE_CONNECT_API_KEY_KEY_PATH"]
      )
    end

    match(type: "appstore", readonly: true, api_key: api_key)
    build_app(
      workspace: "./Runner.xcworkspace",
      scheme: "Runner"
    )
    upload_options = {
      groups: ["Internal"],
      distribute_external: false
    }
    upload_options[:api_key] = api_key if api_key
    upload_to_testflight(upload_options)
  end
end
