name: widgetbook_workspace
description: "Widgetbook workspace for ToPWR mobile app"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.12.0
resolution: workspace

dependencies:
  topwr: any
  flutter:
    sdk: flutter
  widgetbook: ^4.0.0-beta.3
  auto_route: ^11.1.0
  fast_immutable_collections: ^11.1.0
  riverpod: ^3.2.1
  flutter_riverpod: ^3.3.1
  hooks_riverpod: ^3.3.1
  intl: ^0.20.2
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  solvro_config: ^1.8.1-dev.1
  sqflite_common_ffi: ^2.4.1

flutter:
  uses-material-design: true

  fonts:
    - family: ContacsIcons
      fonts:
        - asset: ../../assets/fonts/ContacsIcons.ttf
    - family: BottomNavBarIcons
      fonts:
        - asset: ../../assets/fonts/BottomNavBarIcons.ttf
    - family: IParkingIcons
      fonts:
        - asset: ../../assets/fonts/IParkingIcons.ttf
    - family: StrategicClubBadges
      fonts:
        - asset: ../../assets/fonts/StrategicClubBadges.ttf
    - family: Rubik
      fonts:
        - asset: ../../assets/fonts/rubik/Rubik-Light.ttf
          weight: 300
        - asset: ../../assets/fonts/rubik/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: ../../assets/fonts/rubik/Rubik-Regular.ttf
          weight: 400
        - asset: ../../assets/fonts/rubik/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: ../../assets/fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: ../../assets/fonts/rubik/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: ../../assets/fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: ../../assets/fonts/rubik/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: ../../assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: ../../assets/fonts/rubik/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: ../../assets/fonts/rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: ../../assets/fonts/rubik/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: ../../assets/fonts/rubik/Rubik-Black.ttf
          weight: 900
        - asset: ../../assets/fonts/rubik/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
