builders:
  translatable_generator:
    import: "package:translatable_generator/builder.dart"
    build_extensions: { ".dart": [".translatable.g.dart"] }
    builder_factories: ["translatableBuilder"]
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
