name: translatable_generator
description: A code generator for translatable annotations
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: ^7.3.0
  build: ^2.4.2
  source_gen: ^2.0.0
  path: ^1.8.0
  json_annotation: ^4.9.0
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.4.15
  test: ^1.25.15
