// Scaffold generated by home_widget. Adjust the widget for your needs.

import WidgetKit
import SwiftUI

@main
struct ParkingsHomeWidgetBundle: WidgetBundle {
  var body: some Widget {
    ParkingsHomeWidget()
  }
}
