name: CD - android internal

on:
  workflow_call:
    inputs:
      latest_changelog:
        required: false
        type: string
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: continuous delivery
    steps:
      - uses: actions/checkout@v6

      - name: git crypt unlock
        uses: sliteteam/github-action-git-crypt-unlock@1.3.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Place key.properties
        run: echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

      - name: Decode and place keystore
        run: echo "${{ secrets.GOOGLE_STORE_FILE_JKS_B64 }}" | base64 -d > android/keystore-topwr.keystore

      - name: PLAY_STORE_UPLOAD_KEY decode
        run: echo "${{ secrets.PLAY_STORE_UPLOAD_KEY }}" | base64 -d > android/service-account-key.json

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml

      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Generate files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
          working-directory: android

      - name: Install libsodium
        run: |
          sudo apt-get update
          sudo apt-get install -y libsodium-dev

      - name: Build app bundle
        run: flutter build appbundle --release

      - name: Install Fastlane (Android)
        run: |
          cd android
          bundle install

      - name: Get app version
        id: version
        run: |
          echo "version=$(grep '^version:' pubspec.yaml | sed 's/version:[[:space:]]*//' | tr -d '\r\n ')" >> "$GITHUB_OUTPUT"

      - name: Run Fastlane internal
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          APP_VERSION: ${{ steps.version.outputs.version }}
          CI: true
          LATEST_CHANGELOG: ${{ inputs.latest_changelog }}
        run: |
          cd android
          bundle exec fastlane internal
