name: CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  all-checks:
    name: All checks
    runs-on: macos-latest 

    steps:
      - uses: actions/checkout@v6

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          cache: true 

      - name: Install dependencies
        run: flutter pub get

      - name: Install git-crypt
        run: brew install git-crypt

      - name: git crypt unlock
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
        run: |
          echo "$GIT_CRYPT_KEY" | base64 --decode > secret_key.key
          git-crypt unlock secret_key.key
          rm secret_key.key

      - name: Remove lib/l10n directory
        run: rm -rf lib/l10n/*.dart

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Regenerate the localization files
        run: flutter gen-l10n

      - name: Generate files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Analyze project source
        run: flutter analyze --fatal-infos

      - name: Run custom lints
        run: dart run custom_lint --fatal-infos

      - name: Flutter unit tests
        run: flutter test

  integration-tests:
    name: Integration tests (iOS)
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Install git-crypt
        run: brew install git-crypt

      - name: git crypt unlock
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
        run: |
          echo "$GIT_CRYPT_KEY" | base64 --decode > secret_key.key
          git-crypt unlock secret_key.key
          rm secret_key.key

      - name: Generate files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Pre-build iOS Integration Test App
        run: flutter build ios --debug --no-codesign --simulator

      - name: Boot iOS Simulator
        run: |
          set +e 
          DEVICE_UUID=$(xcrun simctl list devices available | grep "iPhone" | head -n 1 | awk -F'[()]' '{print $2}')
          set -e
          
          if [ -z "$DEVICE_UUID" ]; then
            exit 1
          fi
          
          xcrun simctl boot "$DEVICE_UUID" || true
          xcrun simctl bootstatus "$DEVICE_UUID"
          echo "SIMULATOR_ID=$DEVICE_UUID" >> $GITHUB_ENV

      - name: Run Integration Tests on iOS Simulator
        run: flutter test integration_test/smoke_test.dart -d "$SIMULATOR_ID" --timeout=30m
        timeout-minutes: 45
