on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Example .env
        run: cp example.env .env

      - name: generate files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Hex Color Converters Test
        run: flutter test test/hex_color_converters_test.dart